server:
  port: 8082
  servlet:
    context-path: /v1/customers

spring:
  application:
    name: customer

eureka:
  client:
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka