server:
  port: 8081
  servlet:
    context-path: /employee

spring:
  application:
    name: employee

eureka:
  client:
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka